import { ArrowRight, ArrowUpRight, Mail, Phone, Check, HeartHandshake, BriefcaseBusiness, FileCheck2, UserRound, MessageCircle } from "lucide-react";
import { templateConfig as site, whatsappUrl } from "../../../config/template.config";
import { useReveal } from "../../../core/motion/useReveal";
export function HomePage(){useReveal();return <>
<section className="mono-hero" id="inicio"><div className="container hero-grid" id="conteudo"><div className="mono-hero-content"><span className="mono-kicker">ORIENTAÇÃO PREVIDENCIÁRIA</span><h1>Você teve um filho <em>recentemente?</em></h1><p>{site.hero.description}</p><a className="light-button" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">{site.hero.cta}<ArrowUpRight/></a><div className="hero-assurance"><span><FileCheck2/>Análise individual</span><span><HeartHandshake/>Orientação cuidadosa</span></div></div><div className="hero-image"><div className="hero-ring" aria-hidden="true"/><span className="hero-seal"><HeartHandshake/>INFORMAÇÃO<br/>QUE ACOLHE</span><img src="/assets/maternidade.webp" width="1067" height="1600" fetchPriority="high" alt="Gestante com as mãos sobre a barriga em um ambiente ao ar livre"/><span className="image-caption">Um novo momento.<br/>Informação para os próximos passos.</span></div></div><div className="container hero-note"><span>SALÁRIO-MATERNIDADE</span><p>Você não precisa conhecer todas as regras previdenciárias para buscar orientação.</p></div></section>
<section className="mono-section" id="atuacao"><div className="container"><div className="mono-heading"><div><span className="mono-kicker">ENTENDA O BENEFÍCIO</span><h2>Quem pode <em>ter direito?</em></h2></div><p>O salário-maternidade se destina a pessoas que se afastam de suas atividades por nascimento de filho, adoção ou outras situações previstas na legislação. Os requisitos dependem de cada caso.</p></div><div className="service-cards">{site.services.map((s,i)=><article key={s.title}><div className="card-top">{[<BriefcaseBusiness key="job"/>,<UserRound key="person"/>,<FileCheck2 key="doc"/>,<HeartHandshake key="heart"/>][i]}<span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.description}</p><a href="#contato">Entender meu caso<ArrowUpRight/></a></article>)}</div><p className="section-note">Essas são algumas situações possíveis. O enquadramento depende de análise individual.</p></div></section>
<section className="mono-section about-section" id="escritorio"><div className="container about-grid"><div className="about-photo"><span className="photo-label">Cada história merece<br/><em>um olhar atento.</em></span><img src="/assets/mae-filho.webp" width="1067" height="1600" loading="lazy" alt="Mãe abraçando seu filho ao ar livre"/></div><div className="about-copy"><span className="mono-kicker">WALKER METZKER · ADVOCACIA</span><h2>Clareza para entender.<br/><em>Cuidado para orientar.</em></h2><p>{site.professional.biography}</p><p>Não sabe se você se enquadra? Conte um pouco sobre sua situação. A equipe poderá orientar sobre as informações necessárias e os próximos passos.</p><a className="outline-button" href="#contato">Conversar com a equipe<ArrowRight/></a></div></div></section>
<section className="mono-section process-section" id="analise"><div className="container"><span className="mono-kicker">COMO FUNCIONA</span><h2>O primeiro passo é <em>compreender sua história.</em></h2><div className="process-grid">{[['01','Conte sua situação','Entre em contato e explique brevemente sua dúvida sobre o benefício.'],['02','Receba orientação','A equipe indicará quais informações e documentos são necessários.'],['03','Entenda os caminhos','A análise individual permite orientar sobre os próximos passos possíveis.']].map(([n,t,x])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div><div className="analysis-list"><div className="analysis-visual"><img src="/assets/carteira.webp" width="1200" height="1200" loading="lazy" alt="Carteira de Trabalho e Previdência Social"/></div><div><h3>O que pode ser analisado?</h3><ul>{['Histórico de contribuições','Situação perante o INSS','Data do nascimento ou adoção','Condição profissional','Motivo de eventual negativa'].map(x=><li key={x}><Check/>{x}</li>)}</ul></div></div></div></section>
<section className="mono-section faq-section" id="faq"><div className="container faq-wrap"><span className="mono-kicker">PERGUNTAS FREQUENTES</span><h2>Suas dúvidas, <em>com clareza.</em></h2><div className="faq-list">{site.faqs.map(([q,a],i)=><details key={q}><summary><span>0{i+1}</span>{q}<i>+</i></summary><p>{a}</p></details>)}</div></div></section>
<section className="mono-contact" id="contato"><div className="container contact-box"><div><span className="mono-kicker">VAMOS CONVERSAR</span><h2>Seu caso pode<br/><em>ser diferente.</em></h2><p>As informações desta página são gerais. Entre em contato para verificar se sua situação pode ser analisada.</p><small>No primeiro contato, evite enviar documentos ou informações sensíveis sem orientação.</small></div><div className="contact-actions"><span className="contact-label"><MessageCircle/>Uma conversa pode esclarecer suas dúvidas.</span><img className="contact-visual" src="/assets/contato.webp" width="1200" height="900" loading="lazy" alt=""/><a className="light-button" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Quero analisar meu caso<ArrowUpRight/></a><a href={`tel:+${site.contact.phone}`}><Phone/>{site.phoneLabel}</a><a href={`mailto:${site.contact.email}?cc=${site.contact.emailCopy}`}><Mail/>{site.contact.email}</a><a href={site.contact.instagram} target="_blank" rel="noopener noreferrer">Instagram · @advogadoswm</a><span>Contato: Fellipe Walker</span></div></div></section>
</>}
